# Generated by Django 5.1.2 on 2024-12-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Type 1'), (2, 'Type 2')])),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sum', models.FloatField()),
                ('period', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='gameapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('sum_now', models.FloatField()),
                ('sum_later', models.FloatField()),
                ('period', models.IntegerField()),
                ('scip', models.BooleanField(default=False)),
                ('action_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gameapp.question')),
            ],
        ),
    ]
