# Generated by Django 5.1.2 on 2024-12-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_chance_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chance',
            name='scip',
            field=models.BooleanField(default=False),
        ),
    ]
