# Generated by Django 5.1.2 on 2025-01-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0005_chance_scip'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profession',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameapp.professions'),
        ),
    ]
