# Generated by Django 5.1.2 on 2025-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0006_player_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
