# Generated by Django 5.1.2 on 2025-01-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0007_player_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='scip',
            field=models.BooleanField(default=False),
        ),
    ]
