# Generated by Django 5.1.2 on 2025-01-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_action_scip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('new game', 'New game'), ('started', 'Started'), ('finished', 'Finished')], default='new game', max_length=50),
        ),
    ]
