# Generated by Django 5.1.2 on 2025-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0009_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category',
            field=models.CharField(default='Действие', max_length=100),
        ),
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.CharField(default='Ответ на вопрос', max_length=100),
        ),
        migrations.AddField(
            model_name='chance',
            name='category',
            field=models.CharField(default='Шанс', max_length=100),
        ),
    ]
