version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: docker-app-backend
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
  vue:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: docker-app-frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8080:8080"
    depends_on:
      - django
    environment:
      - NODE_ENV=production
