version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: docker-app-backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8200:8200"
  vue:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: docker-app-frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "8280:8280"
    depends_on:
      - django
    environment:
      - NODE_ENV=production
