version: '3.3'

services:
  db:
    image: postgres
    container_name: docker-app-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    restart: unless-stopped
    ports:
      - "5432:5432"
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: docker-app-backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8200:8200"
    depends_on:
        - db
  vue:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: docker-app-frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "8280:8280"
    depends_on:
      - django
    environment:
      - NODE_ENV=production