# Generated by Django 5.1.2 on 2025-01-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='indexPhoto',
            field=models.IntegerField(default=0),
        ),
    ]
