# Generated by Django 5.1.4 on 2025-02-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_indexphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(default='ovnOhPT0Lp8UKfnlK04z5hxww7oMG5HV', max_length=50),
        ),
    ]
