# Generated by Django 5.1.1 on 2025-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_indexphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(default='Vi8ccjKKkeHGeV87mBxsFJNlSpBJHf4v', max_length=50),
        ),
    ]
