# Generated by Django 5.1.2 on 2025-01-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='pathToPhoto',
            field=models.TextField(default='@/assets/av1.png'),
        ),
    ]
