# Generated by Django 5.1.2 on 2025-01-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_photo_user_pathtophoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pathToPhoto',
        ),
        migrations.AddField(
            model_name='user',
            name='indexPhoto',
            field=models.IntegerField(default=0),
        ),
    ]
